# Generated by Django 2.0.5 on 2018-05-15 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0001_initial'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('idatividade', models.AutoField(db_column='idAtividade', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(max_length=1000)),
                ('conteudo', models.CharField(blank=True, max_length=1000, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('extra', models.CharField(blank=True, max_length=1000, null=True)),
                ('idprofessor', models.ForeignKey(db_column='idProfessor', on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Atividadevinculada',
            fields=[
                ('idatividadevinculada', models.AutoField(db_column='idAtividadeVinculada', primary_key=True, serialize=False)),
                ('rotulo', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('dtiniciorespostas', models.DateField(blank=True, db_column='dtInicioRespostas', null=True)),
                ('dtfimrespostas', models.DateField(blank=True, db_column='dtFimRespostas', null=True)),
                ('idatividade', models.ForeignKey(db_column='idAtividade', on_delete=django.db.models.deletion.DO_NOTHING, to='restrito.Atividade')),
                ('iddisciplinaofertada', models.ForeignKey(db_column='idDisciplinaOfertada', on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Disciplinaofertada')),
                ('idprofessor', models.ForeignKey(db_column='idProfessor', on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('identrega', models.AutoField(db_column='idEntrega', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=40, null=True)),
                ('resposta', models.CharField(blank=True, max_length=1000, null=True)),
                ('dtentrega', models.DateField(db_column='dtEntrega')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dtavaliacao', models.DateField(db_column='dtAvaliacao')),
                ('obs', models.CharField(blank=True, max_length=1000, null=True)),
                ('idaluno', models.ForeignKey(db_column='idAluno', on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Aluno')),
                ('idatividadevinculada', models.ForeignKey(db_column='idAtividadeVinculada', on_delete=django.db.models.deletion.DO_NOTHING, to='restrito.Atividadevinculada')),
                ('idprofessor', models.ForeignKey(db_column='idProfessor', on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacaomatricula',
            fields=[
                ('idsolicitacaomatricula', models.AutoField(db_column='idSolicitacaoMatricula', primary_key=True, serialize=False)),
                ('dtsolicitacao', models.DateField(db_column='dtSolicitacao')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('idaluno', models.ForeignKey(db_column='idAluno', on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Aluno')),
                ('idcoordenador', models.ForeignKey(blank=True, db_column='idCoordenador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Coordenador')),
                ('iddisciplinaofertada', models.ForeignKey(db_column='idDisciplinaOfertada', on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Disciplinaofertada')),
            ],
        ),
    ]
